import type { ScenarioMeta } from "../types/index.js";

export const SCENARIOS: ScenarioMeta[] = [
  {
    id: "ch1",
    audience: "child",
    title: "Meadow of Curiosity",
    subtitle: "Empathy & Friendship",
    description: "In the meadow, a friend feels left out. Practice welcoming others and offering belonging.",
    startSceneId: "e1",
    ageBand: "5-7",
    skills: ["empathy", "friendship_repair", "courage"],
    estimatedMinutes: 4,
  },
  {
    id: "ch2",
    audience: "child",
    title: "Cave of Purpose",
    subtitle: "Worry & Brave",
    description: "Deep in the cave, fear hides brave gifts. Practice naming worry and taking one brave step.",
    startSceneId: "w1",
    ageBand: "8-10",
    skills: ["worry_brave", "empathy", "courage"],
    estimatedMinutes: 5,
  },
  {
    id: "ch3",
    audience: "child",
    title: "Forest of Questions",
    subtitle: "Calm & Repair",
    description: "Murky feelings cloud the forest. Answer with care and practice calm tools and repair.",
    startSceneId: "c1",
    ageBand: "8-10",
    skills: ["calm", "friendship_repair", "self_worth"],
    estimatedMinutes: 4,
  },
  {
    id: "parent_coach",
    audience: "parent",
    title: "Parent Coach Corner",
    subtitle: "Reflect & Guide",
    description: "Review your child’s journey with counselor-style insights and home practice tips.",
    startSceneId: "parent_hub",
    ageBand: "8-10",
    skills: ["empathy", "calm", "courage"],
    estimatedMinutes: 6,
  },
];
